[package]
name = "cindapp"
version = "0.1.0"
authors = ["aj <zencodes@ajjai.in>"]

[dependencies]
iron = "0.5.1"
router = "0.5.1"
serde = "0.9.10"
serde_derive = "0.9.10"
names = "0.11.0"
random = "0.12.2"
json_io = "0.2.0"
chrono = { version = "0.3.0", features = ["serde"] }

